name: ti_printer_plugin
description: "Plugin para comunicación con impresoras termicas."
version: 1.0.1
homepage: https://github.com/jsalvini/ti_printer_plugin
repository: https://github.com/jsalvini/ti_printer_plugin


environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  gbk_codec: ^0.4.0
  hex: ^0.2.0
  image: ^4.2.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: TiPrinterPlugin
      windows:
        pluginClass: TiPrinterPluginCApi

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/resources/capabilities.json
    - packages/ti_printer_plugin/resources/capabilities.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
